name: CommentIssue
on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # - name: Install preflight
      #   run: yarn global add @upleveled/preflight

      - name: Say Hello to mr. Roboto
        run: node ./scripts/mr-bot-action.js ${{ secrets.GITHUB_TOKEN }}
        inputs:
          token: ${{ secrets.GITHUB_TOKEN }}
        # env:
        #   MY_STRING: ${{ toJson(github.event.issue) }}
        id: random-color-generator

      # - name: run preflight
      #   run: |
      #     pwd
      #     cd ./fixtures/__temp/react-passing
      #     preflight

      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       This is a multi-line test comment
      #       - With GitHub **Markdown** :sparkles:
      #       - Created by [create-or-update-comment][1]

      #       Text is: ${{ github.event.comment.body }}
      #       preflight:
      #       ```sh
      #       ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
      #       ```
      #       [1]: https://github.com/peter-evans/create-or-update-comment
      #     reactions: '+1'
