name: CommentIssue
on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Say Hello to mr. Roboto
        run: node ./scripts/mr-bot.js

      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
