name: CommentIssue
on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Say Hello to mr. Roboto
        run: node ./scripts/mr-bot.js ${{ toJSON(github.event.issue) }}
        env:
          MY_ENV: ${{ github.event.issue.url }}
        id: random-color-generator

      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - run: |
          echo "Comment on issue #${{ github.event.issue.body }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            Text is: ${{ github.event.comment.body }}
            The color is: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
